es_name: "OpenES"
problem_type: "gridworld_meta_b"
normalize: false
es_config:
  pop_size: 400
  init_stdev: 0.07
  decay_stdev: 0.999
  limit_stdev: 0.01
  optimizer: "adam"
  optimizer_config:
    lrate_init: 0.02
    lrate_decay: 0.999
    lrate_limit: 0.001
    momentum: 0.0
policy: "MetaRNN"
hidden_size: 64
num_tests: 100
n_repeats: 16
max_iter: 1000
test_interval: 100
log_interval: 25
seed: 2
gpu_id: 0
debug: false
spawn_prob: 0.005

